# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_equal_bis <- function(v, nombre) {
    .Call(`_projet_which_equal_bis`, v, nombre)
}

Init_b_and_b_rcpp <- function(G, P, R) {
    .Call(`_projet_Init_b_and_b_rcpp`, G, P, R)
}

cout_min_rcpp <- function(SP) {
    .Call(`_projet_cout_min_rcpp`, SP)
}

test_chemin_trouve_rcpp <- function(SP, G) {
    .Call(`_projet_test_chemin_trouve_rcpp`, SP, G)
}

elagage_rcpp <- function(cout_opti, SP) {
    .Call(`_projet_elagage_rcpp`, cout_opti, SP)
}

delete_chemin_rcpp <- function(chemin, SP) {
    .Call(`_projet_delete_chemin_rcpp`, chemin, SP)
}

projet_dispo_rcpp <- function(chemin, G, P) {
    .Call(`_projet_projet_dispo_rcpp`, chemin, G, P)
}

branch_rcpp <- function(chemin, G, P, R) {
    .Call(`_projet_branch_rcpp`, chemin, G, P, R)
}

#'Affectation par méthode branch and bound
#'
#' @description fonction de simulation d'une attribution avec la méthode du branch and bound
#' @param G contient les groupes d'élèves
#' @param P contient les projets et leurs capacités maximales
#' @param R matrice qui contient l'ordre de préférence de chaque groupe
#' @return une attribution d'élèves à des projets optimisée
#' @export
branch_and_bound_rcpp <- function(G, P, R) {
    .Call(`_projet_branch_and_bound_rcpp`, G, P, R)
}

which_equal <- function(v, nombre) {
    .Call(`_projet_which_equal`, v, nombre)
}

objectif_rcpp <- function(X, G, R) {
    .Call(`_projet_objectif_rcpp`, X, G, R)
}

taille_groupe_rcpp <- function(G) {
    .Call(`_projet_taille_groupe_rcpp`, G)
}

binarise_rcpp <- function(i, n, m) {
    .Call(`_projet_binarise_rcpp`, i, n, m)
}

produit_scalaire_rcpp <- function(U, V) {
    .Call(`_projet_produit_scalaire_rcpp`, U, V)
}

produit_vecteur_matrice <- function(V, M) {
    .Call(`_projet_produit_vecteur_matrice`, V, M)
}

#' Affectation par énumération des possibilités
#'
#' @description Affectation des élèves à un projet par ordre des voeux et d'inscription
#' @param G une liste des groupes d'élèves
#' @param P une liste de projets
#' @param R une mactrice de voeux de chaque groupe de G
#' @return la matrice d'attribution des projets par élève et par groupe
#' @export
enumeration_rcpp <- function(G, P, R) {
    .Call(`_projet_enumeration_rcpp`, G, P, R)
}

is_elem <- function(n, v) {
    .Call(`_projet_is_elem`, n, v)
}

produit_scalaire <- function(U, V) {
    .Call(`_projet_produit_scalaire`, U, V)
}

#' Affectation par méthode gloutonne
#'
#' @description Affectation des élèves à un projet par ordre des voeux et d'inscription
#' @param G une liste des groupes d'élèves
#' @param P une liste de projets
#' @param R une matrice de voeux de chaque groupe de G
#' @return la matrice d'attribution des projets par élève et par groupe
#' @export
glouton_rcpp <- function(G, P, R) {
    .Call(`_projet_glouton_rcpp`, G, P, R)
}

#' Which algorithme using C++
#' 
#' @param v un vector
#' @param nombre un nombre
#' @return renvoie l'indice du vecteur où v[ind] = nombre (sinon renvoie -1)
#' @export 
which_is_equal <- function(v, nombre) {
    .Call(`_projet_which_is_equal`, v, nombre)
}

#' is_element algorithme using C++
#' 
#' @param v un vector
#' @param n un nombre
#' @return renvoie si n appartient à v ou non
#' @export
is_element <- function(n, v) {
    .Call(`_projet_is_element`, n, v)
}

#' comptage élève algorithme using C++
#' 
#' @param G une liste de groupe d'étudiant
#' @return le nombre d'étudiant total
#' @export
comptage_eleve <- function(groupe) {
    .Call(`_projet_comptage_eleve`, groupe)
}

#' Méthode lottery algorithm using C++
#' 
#' @param P une liste de projet avec des équipes de projet
#' @param G une liste de groupe d'étudiant
#' @param R une liste de voeu classée par ordre de priorité pour chaque groupe
#' @return renvoie une matrice X de taille (nb eleves,4) telle que chaque colonne correspond à l'élève, son groupe, son projet et son équipe-projet
#' @export
lottery_rcpp <- function(P, G, R) {
    .Call(`_projet_lottery_rcpp`, P, G, R)
}

rcpp_hello_world <- function() {
    .Call(`_projet_rcpp_hello_world`)
}

