# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

which_is_equal <- function(v, nombre) {
    .Call(`_projet_which_is_equal`, v, nombre)
}

is_element <- function(n, v) {
    .Call(`_projet_is_element`, n, v)
}

lottery_rcpp <- function(P, G, R) {
    .Call(`_projet_lottery_rcpp`, P, G, R)
}

rcpp_hello_world <- function() {
    .Call(`_projet_rcpp_hello_world`)
}

